#!/usr/bin/env bash

## Description: Run tableplus against current db
## Usage: tableplus
## Example: "ddev tableplus"

if [ "${DDEV_PROJECT_STATUS}" != "running" ] && [ -z "$no_recursion" ]; then
  echo "Project ${DDEV_PROJECT} is not running, starting it"
  ddev start
  start_exit_code=$?
  if [ $start_exit_code -ne 0 ]; then
    exit $start_exit_code
  fi
  # run this script again, as the environment is updated after "ddev start"
  no_recursion=true ddev "$(basename "$0")" "$@"
  exit $?
fi
# DDEV_DATABASE is type:version (mariadb:10.5), we only want the type
DB_TYPE=${DDEV_DATABASE%:*}
DB_HOST="127.0.0.1"
DB_PORT=$DDEV_HOST_DB_PORT
DB_USER="db"
DB_PASS="db"
DB_NAME="db"

query="${DB_TYPE}://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

case $OSTYPE in
  linux-gnu)
    echo "Not supported on Linux (see .ddev/commands/host/tableplus)"
    ;;

  "darwin"*)
    open "$query" &
    echo "Attempted to launch tableplus for macos"
    ;;

  "win*"* | "msys"*)
    start "$query" & 
    echo "Attempted to launch tableplus for windows"
    ;;
esac
